In [5]:
import xlwings as xw
import numpy as np

app = xw.App(visible=False)
book = xw.Book()
sheet2 = book.sheets.add()
sheet2["A1"].value = np.arange(150).reshape(30,5)

# Loop para adicionar 1 a cada célula
import time
start_time = time.time()
for cell in sheet2["A1:E30"]:
    cell.value += 1
end_time = time.time()
print(f"Tempo de execução: {end_time - start_time} segundos")

# Usando options para adicionar 1 a cada célula
start_time = time.time()
values = sheet2["A1:E30"].options(np.array).value
sheet2["A1"].value = values + 1
end_time = time.time()
print(f"Tempo de execução: {end_time - start_time} segundos")

Tempo de execução: 4.128464937210083 segundos
Tempo de execução: 0.17331862449645996 segundos


In [ ]:
# - O uso da opção options para adicionar 1 a cada célula foi significativamente mais rápido do que o loop.
# - Isso ocorre porque a opção options permite que o xlwings trabalhe com arrays do NumPy, o que é mais eficiente do que iterar sobre células individuais.

In [7]:
import numpy as np

array = np.arange(150).reshape(30, 5)
print(array)


[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [ 40  41  42  43  44]
 [ 45  46  47  48  49]
 [ 50  51  52  53  54]
 [ 55  56  57  58  59]
 [ 60  61  62  63  64]
 [ 65  66  67  68  69]
 [ 70  71  72  73  74]
 [ 75  76  77  78  79]
 [ 80  81  82  83  84]
 [ 85  86  87  88  89]
 [ 90  91  92  93  94]
 [ 95  96  97  98  99]
 [100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]
 [125 126 127 128 129]
 [130 131 132 133 134]
 [135 136 137 138 139]
 [140 141 142 143 144]
 [145 146 147 148 149]]


In [21]:
import xlwings as xw
import numpy as np

app = xw.App(visible=False)
wb = xw.Book()
sheet2 = wb.sheets.add()
sheet2["A1"].value = np.arange(150).reshape(30,5)
wb.save("C:\\Users\\luist\\Documents\\planilha.xlsx")
app.quit()


In [ ]:
# O que está acontecendo:
# - np.arange(100) cria um array com 100 elementos.
# - reshape(30, 6) tenta reorganizar esses 100 elementos em uma matriz com 30 linhas e 6 colunas.
# - No entanto, 30 linhas e 6 colunas dariam um total de 180 elementos (30 x 6 = 180), o que não é compatível com os 100 elementos do array original.


In [25]:
import xlwings as xw
import numpy as np

app = xw.App(visible=False)
wb = xw.Book()
sheet = wb.sheets[0]
array = np.arange(100).reshape(10, 10)
sheet["A1"].value = array
nome_arquivo = "planilha"
numero = 2
wb.save("C:\\Users\\luist\\Documents\\planilha.xlsx")
wb.save(f"{nome_arquivo}_{numero}.xlsx")  # Salva com um nome diferente
app.quit()


In [ ]:
Comandos que mencionei anteriormente (cd, dir, start) são usados para verificar e manipular arquivos e pastas no prompt do Anaconda (ou no cmd do Windows).

Comandos para verificar arquivos e pastas:
- cd: Muda para um diretório específico.
- dir: Lista os arquivos e pastas no diretório atual.
- ls: Lista os arquivos e pastas no diretório atual (similar ao dir, mas com mais opções).
- pwd: Mostra o caminho do diretório atual.

Comandos para manipular arquivos e pastas:
- mkdir: Cria uma nova pasta.
- rmdir: Remove uma pasta vazia.
- del: Remove um arquivo.
- copy: Copia um arquivo.
- move: Move um arquivo ou pasta.
- rename: Renomeia um arquivo ou pasta.

Comandos para abrir arquivos:
- start: Abre um arquivo com o programa associado.


In [ ]:
Para localizar a planilha criada no prompt do Anaconda, você pode seguir os passos abaixo:

Passos:
1. Abra o prompt do Anaconda.
2. Digite o comando cd seguido do caminho onde você salvou a planilha. Por exemplo: cd C:\Users\luist\Documents
3. Pressione Enter para mudar para o diretório especificado.
4. Digite o comando dir para listar os arquivos no diretório atual.
5. Procure pelo nome da planilha que você criou (por exemplo, "planilha_2.xlsx").

Exemplo:

C:\Users\luist>cd C:\Users\luist\Documents
C:\Users\luist\Documents>dir
 Volume in drive C has no label.
 Volume serial number is 12345678

 Directory of C:\Users\luist\Documents

02/02/2023  10:00 AM    <DIR>          .
02/02/2023  10:00 AM    <DIR>          ..
02/02/2023  10:00 AM               123 planilha_2.xlsx
               1 File(s)            123 bytes
               2 Dir(s)  123456789 bytes free


Ou, se você quiser abrir a planilha diretamente do prompt do Anaconda:
1. Digite o comando start seguido do nome da planilha. Por exemplo: start planilha_2.xlsx
2. Pressione Enter para abrir a planilha no Excel.

Exemplo:

C:\Users\luist\Documents>start planilha_2.xlsx

In [28]:
import xlwings as xw
import numpy as np

app = xw.App(visible=False)
wb = xw.Book()

# Cria as planilhas

shapes = [(10, 10), (5, 10), (20, 10)]
for i, shape in enumerate(shapes):
    sheet = wb.sheets.add()
    sheet.name = f"Planilha {i+1}"
    array = np.arange(shape[0]*shape[1]).reshape(shape)
    sheet["A1"].value = array

wb.save("planilha.xlsx")
app.quit()


In [ ]:
Aqui está o código equivalente usando o pandas:

Exemplo:

import pandas as pd
import numpy as np

# Cria as planilhas

shapes = [(10, 10), (5, 10), (20, 10)]
with pd.ExcelWriter("planilha.xlsx") as writer:
    for i, shape in enumerate(shapes):
        array = np.arange(shape[0]*shape[1]).reshape(shape)
        df = pd.DataFrame(array)
        df.to_excel(writer, sheet_name=f"Planilha {i+1}", index=False)


Nesse exemplo, estamos usando o pd.ExcelWriter para criar um arquivo de Excel e escrever as planilhas nele. Cada planilha é criada a partir de um DataFrame do pandas, que é gerado a partir do array numpy.

Observações:
- O pd.ExcelWriter é usado para criar um arquivo de Excel e escrever as planilhas nele.
- O df.to_excel é usado para escrever o DataFrame no arquivo de Excel.
- O sheet_name é usado para especificar o nome da planilha.
- O index=False é usado para não incluir o índice do DataFrame na planilha.

Esse código é mais conciso e fácil de ler do que o código original, e também é mais eficiente porque não requer a criação de um objeto xlwings.App.

In [36]:
import pandas as pd
import numpy as np

# Cria as planilhas
shapes = [(10, 10), (5, 10), (20, 10)]
with pd.ExcelWriter("planilhas.xlsx") as writer:
    for i, shape in enumerate(shapes):
        array = np.arange(shape[0]*shape[1]).reshape(shape)
        df = pd.DataFrame(array)
        df.to_excel(writer, sheet_name=f"Planilhas {i+1}", index=False)
        